train: D:\zcasp\Documents\GitHub\Robocup\MachineLearn\images\train
test: D:\zcasp\Documents\GitHub\Robocup\MachineLearn\images\val
val: D:\zcasp\Documents\GitHub\Robocup\MachineLearn\test_images

#Classes
nc: 12

#classes names
#replace all class names list with your classes names
names: ['water', 'cola', 'sprite', 'orange juice', 'biscuit','chip','lays','bread','cookie','handwash','dishsoap','shampoo']